### ISSUE TITLE
[Tracking Issue] Streamlining CI deployments

### ISSUE THREAD

**Issue by konturn** [tlc-pack/ci#25]
This issue exists to track progress on the effort to streamline deployments to Jenkins CI. Specifically, it outlines a short list of features which will enable regular contributors to this repository to deploy to Jenkins in accordance with the conclusions in https://github.com/tlc-pack/ci/issues/24:
- [x] Combine CI repositories into one for the sake of simplicity.
- [x] Create `DEPLOYERS.md` file in this repository with a list of Github users with permissions to deploy to Jenkins.
- [x] If a user in `DEPLOYERS.md` comments `deploy` in a PR and the PR is approved and merged by a contributor, then trigger deploy workflow on merge to main.
- [ ] Port CI repo to Apache Github Organization.

**Comment by konturn** [comment]
cc @areusch @driazati @Mousius @leandron

**Comment by driazati** [comment]
its not clear if the last point needs to happen now, closing this issue so we can disable issues in this repo. If that comes up again we can revisit it in apache/tvm
